version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_6649010018
    ports:
      - "8418:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - ./wordpress/html:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress/web.conf:/etc/apache2/sites-available/web.conf:ro
      - ./wordpress/web.conf:/etc/apache2/sites-enabled/web.conf:ro
    networks:
      - wordpress-network

  db:
    image: mysql:5.7
    container_name: mysql_6649010018
    restart: always
    ports:
      - "3418:3306"
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wordpress-network

networks:
  wordpress-network:

volumes:
  wordpress_data:
  db_data:
